"""RF spectrum planning: TV-channel exclusion + intermodulation-aware
frequency suggestion, modeled on how RF coordination tools like Shure
Wireless Workbench and Sennheiser WSM work at a high level -- take a
region's TV/regulatory band plan, subtract occupied TV channels, then
pick new carriers that keep clear of 3rd-order intermodulation products
and a minimum spacing from everything already in use.

This is a planning aid based on publicly documented band plans, not a
substitute for checking local regulations or a live TV-station database
(e.g. the FCC's own tools) before an actual deployment.
"""

REGIONS = {
    'us_fcc': {
        'name': 'United States (FCC)',
        'tv_channel_start': 14,
        'tv_channel_end': 51,
        'tv_channel_width_mhz': 6,
        'tv_band_start_mhz': 470,
        # Simplified: usable, license-exempt/coordinated wireless-mic spectrum
        # is the interleaved (unused-locally) UHF TV whitespace 470-608 MHz,
        # plus the narrow 614-616 MHz guard band. The 600 MHz duplex gap and
        # exact channel 37/51 edge rules vary by market post-2017 repack --
        # verify locally (e.g. via the FCC's TV query tools) before relying
        # on this for a real deployment.
        'wireless_mic_ranges_mhz': [(470, 608), (614, 616)],
        'notes': ("Wireless mics may use unoccupied (interleaved) UHF TV channels 470-608 MHz "
                  "plus the 614-616 MHz guard band. Exact local availability (600 MHz duplex gap, "
                  "channel 37 radio astronomy band, etc.) varies by market -- confirm before deploying."),
    },
    'eu_etsi': {
        'name': 'European Union / UK (ETSI)',
        'tv_channel_start': 21,
        'tv_channel_end': 48,
        'tv_channel_width_mhz': 8,
        'tv_band_start_mhz': 470,
        # Channel 38 (606-614 MHz) is the shared PMSE/wireless-mic band across
        # most of Europe and the UK; 470-606 MHz is interleaved TV whitespace
        # that needs local/site coordination.
        'wireless_mic_ranges_mhz': [(470, 606), (606, 614)],
        'notes': ("Channel 38 (606-614 MHz) is shared PMSE spectrum for wireless mics across "
                  "much of Europe/UK; 470-606 MHz is interleaved spectrum requiring local "
                  "coordination. Rules vary by country -- verify with your national regulator."),
    },
}

IM_MARGIN_KHZ_DEFAULT = 250   # min. separation between a carrier and any 3rd-order IM product
MIN_SPACING_MHZ_DEFAULT = 1.0  # baseline min. separation between any two carriers
SUGGEST_STEP_KHZ_DEFAULT = 25  # grid resolution when searching for candidate frequencies


def tv_channel_frequency(region_key, channel_num):
    region = REGIONS[region_key]
    width = region['tv_channel_width_mhz']
    start = region['tv_band_start_mhz'] + (channel_num - region['tv_channel_start']) * width
    return (round(start, 3), round(start + width, 3))


def usable_ranges(region_key, occupied_tv_channels):
    """Legal wireless-mic ranges for the region, minus the given occupied TV channels."""
    region = REGIONS[region_key]
    excluded = [tv_channel_frequency(region_key, ch) for ch in occupied_tv_channels]
    segments = list(region['wireless_mic_ranges_mhz'])
    for (elo, ehi) in excluded:
        next_segments = []
        for (slo, shi) in segments:
            if ehi <= slo or elo >= shi:
                next_segments.append((slo, shi))
                continue
            if elo > slo:
                next_segments.append((slo, elo))
            if ehi < shi:
                next_segments.append((ehi, shi))
        segments = next_segments
    return segments


def third_order_im_products(frequencies_mhz):
    products = set()
    for f1 in frequencies_mhz:
        for f2 in frequencies_mhz:
            if f1 == f2:
                continue
            products.add(round(2 * f1 - f2, 4))
    return products


def find_im_conflicts(frequencies_mhz, im_margin_khz=IM_MARGIN_KHZ_DEFAULT):
    """For every frequency, flag it if it sits within the margin of a 3rd-order
    IM product generated by any OTHER pair in the set."""
    margin = im_margin_khz / 1000
    conflicts = []
    for target in frequencies_mhz:
        others = [f for f in frequencies_mhz if f != target]
        for f1 in others:
            for f2 in others:
                if f1 == f2:
                    continue
                im = 2 * f1 - f2
                if abs(im - target) < margin:
                    conflicts.append({
                        'frequency': target,
                        'im_product': round(im, 4),
                        'generated_by': [f1, f2],
                    })
    return conflicts


def _conflicts_with_set(candidate, chosen, min_spacing_mhz, margin_mhz):
    for c in chosen:
        if abs(candidate - c) < min_spacing_mhz:
            return True
    for f1 in chosen:
        for f2 in chosen:
            if f1 == f2:
                continue
            im = 2 * f1 - f2
            if abs(im - candidate) < margin_mhz:
                return True
    for c in chosen:
        im1 = 2 * candidate - c
        im2 = 2 * c - candidate
        for other in chosen:
            if other == c:
                continue
            if abs(im1 - other) < margin_mhz or abs(im2 - other) < margin_mhz:
                return True
    return False


def suggest_frequencies(region_key, occupied_tv_channels, existing_mhz, count,
                         min_spacing_mhz=MIN_SPACING_MHZ_DEFAULT,
                         im_margin_khz=IM_MARGIN_KHZ_DEFAULT,
                         step_khz=SUGGEST_STEP_KHZ_DEFAULT):
    """Greedily pick `count` new frequencies inside the region's usable
    spectrum that keep min_spacing_mhz from, and avoid 3rd-order IM
    conflicts with, everything already in `existing_mhz` and each other."""
    ranges = usable_ranges(region_key, occupied_tv_channels)
    step = step_khz / 1000
    margin_mhz = im_margin_khz / 1000
    chosen = list(existing_mhz)
    suggested = []
    for (lo, hi) in ranges:
        f = lo
        while f <= hi and len(suggested) < count:
            candidate = round(f, 4)
            if not _conflicts_with_set(candidate, chosen, min_spacing_mhz, margin_mhz):
                chosen.append(candidate)
                suggested.append(candidate)
            f += step
        if len(suggested) >= count:
            break
    return suggested
